### ISSUE TITLE
שגיאה בהגדרה removeInvalidChars: true ברמת הראוטר

### ISSUE THREAD

**Issue by abaye123** [ShlomoCode/yemot-router2#43]
#שגיאה בהגדרה removeInvalidChars: true ברמת הראוטר

כשאני מגדיר removeInvalidChars: true ברמת הנתב תחת ברירות המחדל, כך:

`import { YemotRouter } from 'yemot-router2';
import express from 'express';

export const app = express();

export const router = YemotRouter({
    printLog: true,
    timeout: 300000,
    uncaughtErrorHandler: (error, call) => {
        console.log(`Uncaught error in ${call.req.path} from ${call.phone}. error stack: ${error.stack}`);
        return call.id_list_message([{ type: 'text', data: 'התרחשה שגיאה. פנה למנהל המערכת' }]);
    },
    defaults: {
        removeInvalidChars: true
    }
});

router.all('*', function (call) {
    console.log(`General request to an unspecified address. url: ${call.req.path} from ${call.phone} to ${call.ApiDID}`);
    call.id_list_message([{ type: 'text', data: '.כתובת לא מוכרת בשרת' }]);
});

export default router;`

מתקבלת השגיאה הבאה:

`
[0637ded3ada490d8854e3b03c674b4ff924a948c]: 📞 new call - from 0555555555
General request to an unspecified address. url: / from 0555555555 to 0777777777
[0637ded3ada490d8854e3b03c674b4ff924a948c]: 💥 Uncaught error. applying uncaughtErrorHandler (file:///var/www/production/node_modules/yemot-router2/lib/response_functions.js:118:15)
Uncaught error in / from 0555555555. error stack: CallError: message '.כתובת לא מוכרת בשרת' has invalid characters for yemot: .
    at validateCharsForTTS (file:///var/www/el/node_modules/yemot-router2/lib/response_functions.js:118:15)
    at makeMessagesData (file:///var/www/el/node_modules/yemot-router2/lib/response_functions.js:137:13)
    at Call.id_list_message (file:///var/www/el/node_modules/yemot-router2/lib/call.js:239:34)
    at file:///var/www/el/ph/router_calls.js:21:10
    at makeNewCall (file:///var/www/el/node_modules/yemot-router2/lib/yemot_router.js:73:19)
    at file:///var/www/el/node_modules/yemot-router2/lib/yemot_router.js:152:29
    at Layer.handle [as handle_request] (/var/www/el/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/el/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/var/www/el/node_modules/express/lib/router/route.js:119:3)
    at Layer.handle [as handle_request] (/var/www/el/node_modules/express/lib/router/layer.js:95:5)
💥 Error in uncaughtErrorHandler! process is crashing
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
`

**Comment by ShlomoCode** [comment]
תודה על הדיווח. פתרון זמני:
```
defaults: {
    id_list_message: {
        removeInvalidChars: true
    },
    read: {
        removeInvalidChars: true
    }
}
```

**Comment by abaye123** [comment]
אכן זה עובד,

**Comment by ashuvax** [comment]
יותר נכון ככה:
    defaults: {
        id_list_message: {
            removeInvalidChars: true
        },
        read: {
            record: {
                removeInvalidChars: true
            },
            stt: {
                removeInvalidChars: true
            },
            tap: {
                removeInvalidChars: true
            }
        }
    }

**Comment by ShlomoCode** [comment]
@ashuvax 
באיזה מקרה ההגדרה הקודמת לא עובדת לך? זה לא אמור להשפיע יותר ככה

**Comment by ashuvax** [comment]
אה אוקיי מצוין!

**Comment by abaye123** [comment]
@ShlomoCode יש בעיה מסוימת, עדיין לא עליתי על זה במדוייק,
אבל קיבלתי אתמול את השגיאה הבאה, (בגלל התו ')

`2024-07-24T20:06:37: [31m[99d85b8c4175dbb7a2e6d093fe44d62907ace143]: 💥 Uncaught error. applying uncaughtErrorHandler (file:///var/www/app/node_modules/yemot-router2/lib/response_functions.js:118:15)[39m
2024-07-24T20:06:37: Uncaught error in / from 0555555555. error stack: CallError: message 'על ידי מג'נון למשך 3 שעות, בתאריך יום רביעי, 24 ביולי 2024 17:34' has invalid characters for yemot: [31m'[39m`

וזה עם ההגדרה למעלה, השגיאה הזו נזרקת כשיש תו שגוי ולא מוגדרת הסרה, או רק כשמוגדרת הסרה שקטה והיא נכשלת משום מה?
(מסובך לי כרגע לבצע טסט)

**Comment by ShlomoCode** [comment]
ההודעה הזאת נזרקת רק אם הראוטר לא ניסה לבצע הסרה שקטה, ראה [כאן](https://github.com/ShlomoCode/yemot-router2/blob/master/lib/response_functions.js#L114-L139)
אם אתה מקבל את השגיאה הזאת זה אומר שההגדרה שהראוטר חישב בנקודה זו היא שלא צריך להסיר באופן שקט ולכן הוא זרק שגיאה

**Comment by abaye123** [comment]
בדקתי קצת לעומק, ונראה שההסרה עם הפיתרון השמני שהציע @ShlomoCode לא פועלת בread אלא רק בid_list_message.

פתרתי לע"ע את הבעיה ע"י שימוש בשילוב של הכל

`    defaults: {
        removeInvalidChars: true,
        id_list_message: {
            removeInvalidChars: true
        },
        read: {
            removeInvalidChars: true,
            
            record: {
                removeInvalidChars: true
            },
            stt: {
                removeInvalidChars: true
            },
            tap: {
                removeInvalidChars: true
            }
        }
    }`

(הכתיבה כמו שמופיע בתיעוד לבד, עדיין לא משפיעה על כלום)
